config/routes.rb
Rails.application.routes.draw do
  get 'products' => 'products#index'

  post 'products' => 'products#create' 
  get 'products/new' => 'products#new'

  get 'products/:id' => 'products#show', as: 'product'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

    def index
        @products = Product.all
      end

  def show
    @product = Product.find(params[:id])
  end

  def new
  end

  def new
    @product = Product.new
  end

  def create
    # make a new product with what product_params returns (which is a method we're calling)
    @product = Product.new(product_params)
    if @product.save
      # if the save for the product was successful, go to show.html.erb
      redirect_to product_url(@product)
    else
      # otherwise render the view associated with the action :new (i.e. new.html.erb)
      render :new
    end
  end

  private
  def product_params
    params.require(:product).permit(:name, :description, :price, :url)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WebStore</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/products/index.html.erb
<h1>Products<h1>
<%= link_to 'add product', products_new_path %>
<% @products.each do |product| %>
  <p><%= product.name %></p>
  <p><%= product.description %> </p>
  <p><%=product.price%></p>
  <%= link_to 'more info on product', product.url, target: :_blank %>
  <%=link_to 'show product', product_path(product)%>

<% end %>

app/views/products/new.html.erb
<h1>Add a product</h1>
<%= form_for @product do |f| %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </p>
   <p>
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </p>
  <p>
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </p>
  <p>
    <%= f.submit "Save" %>
  </p>
<% end %>

app/views/products/show.html.erb
<p><%= @product.name %>, <%= @product.description %></p>
<%= @product.url %>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>